allowBuilds:
  ejs: true
  hexo-util: true
  inferno: true
overrides:
  '@babel/core': 7.29.7
  '@babel/plugin-transform-modules-systemjs': 7.29.7
  brace-expansion: 1.1.13
  js-yaml: 4.2.0
  minimist: 0.2.4
  picomatch: 2.3.2
